#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-desc
Version  : 1.2.0
Release  : 29
URL      : https://cran.r-project.org/src/contrib/desc_1.2.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/desc_1.2.0.tar.gz
Summary  : Manipulate DESCRIPTION Files
Group    : Development/Tools
License  : MIT
BuildRequires : R-assertthat
BuildRequires : R-backports
BuildRequires : R-cli
BuildRequires : R-rprojroot
BuildRequires : R-withr
BuildRequires : buildreq-R

%description
# desc
> Parse DESCRIPTION files
[![Linux Build Status](https://travis-ci.org/r-lib/desc.svg?branch=master)](https://travis-ci.org/r-lib/desc)
[![Windows Build status](https://ci.appveyor.com/api/projects/status/github/r-lib/desc?svg=true)](https://ci.appveyor.com/project/gaborcsardi/desc)
[![](http://www.r-pkg.org/badges/version/desc)](http://www.r-pkg.org/pkg/desc)
[![CRAN RStudio mirror downloads](http://cranlogs.r-pkg.org/badges/desc)](http://www.r-pkg.org/pkg/desc)
[![Coverage Status](https://img.shields.io/codecov/c/github/r-lib/desc/master.svg)](https://codecov.io/github/r-lib/desc?branch=master)

%prep
%setup -q -c -n desc

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1552905498

%install
export SOURCE_DATE_EPOCH=1552905498
rm -rf %{buildroot}
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library desc
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library desc
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library desc
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc  desc || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/desc/DESCRIPTION
/usr/lib64/R/library/desc/DESCRIPTION2
/usr/lib64/R/library/desc/INDEX
/usr/lib64/R/library/desc/LICENSE
/usr/lib64/R/library/desc/Meta/Rd.rds
/usr/lib64/R/library/desc/Meta/features.rds
/usr/lib64/R/library/desc/Meta/hsearch.rds
/usr/lib64/R/library/desc/Meta/links.rds
/usr/lib64/R/library/desc/Meta/nsInfo.rds
/usr/lib64/R/library/desc/Meta/package.rds
/usr/lib64/R/library/desc/NAMESPACE
/usr/lib64/R/library/desc/NEWS.md
/usr/lib64/R/library/desc/R/desc
/usr/lib64/R/library/desc/R/desc.rdb
/usr/lib64/R/library/desc/R/desc.rdx
/usr/lib64/R/library/desc/README.Rmd
/usr/lib64/R/library/desc/README.md
/usr/lib64/R/library/desc/help/AnIndex
/usr/lib64/R/library/desc/help/aliases.rds
/usr/lib64/R/library/desc/help/desc.rdb
/usr/lib64/R/library/desc/help/desc.rdx
/usr/lib64/R/library/desc/help/paths.rds
/usr/lib64/R/library/desc/html/00Index.html
/usr/lib64/R/library/desc/html/R.css
/usr/lib64/R/library/desc/tests/testthat.R
/usr/lib64/R/library/desc/tests/testthat/D1
/usr/lib64/R/library/desc/tests/testthat/D2
/usr/lib64/R/library/desc/tests/testthat/D3
/usr/lib64/R/library/desc/tests/testthat/D4
/usr/lib64/R/library/desc/tests/testthat/D5
/usr/lib64/R/library/desc/tests/testthat/D6
/usr/lib64/R/library/desc/tests/testthat/D7
/usr/lib64/R/library/desc/tests/testthat/D8
/usr/lib64/R/library/desc/tests/testthat/files/DESCRIPTION
/usr/lib64/R/library/desc/tests/testthat/fixtures/notpkg_1.0.tar.gz
/usr/lib64/R/library/desc/tests/testthat/fixtures/pkg_1.0.0.tar.gz
/usr/lib64/R/library/desc/tests/testthat/fixtures/pkg_1.0.0.tgz
/usr/lib64/R/library/desc/tests/testthat/fixtures/pkg_1.0.0.zip
/usr/lib64/R/library/desc/tests/testthat/fixtures/pkg_1.0.0_R_x86_64-pc-linux-gnu.tar.gz
/usr/lib64/R/library/desc/tests/testthat/fixtures/xxx.gz
/usr/lib64/R/library/desc/tests/testthat/fixtures/xxx.tar.gz
/usr/lib64/R/library/desc/tests/testthat/fixtures/xxx.zip
/usr/lib64/R/library/desc/tests/testthat/helper.R
/usr/lib64/R/library/desc/tests/testthat/output/to_latex.tex
/usr/lib64/R/library/desc/tests/testthat/test-archives.R
/usr/lib64/R/library/desc/tests/testthat/test-assertions.R
/usr/lib64/R/library/desc/tests/testthat/test-authors.R
/usr/lib64/R/library/desc/tests/testthat/test-built.R
/usr/lib64/R/library/desc/tests/testthat/test-checks.R
/usr/lib64/R/library/desc/tests/testthat/test-collate.R
/usr/lib64/R/library/desc/tests/testthat/test-create.R
/usr/lib64/R/library/desc/tests/testthat/test-deps.R
/usr/lib64/R/library/desc/tests/testthat/test-desc.R
/usr/lib64/R/library/desc/tests/testthat/test-encoding.R
/usr/lib64/R/library/desc/tests/testthat/test-idempotent.R
/usr/lib64/R/library/desc/tests/testthat/test-non-oo.R
/usr/lib64/R/library/desc/tests/testthat/test-queries.R
/usr/lib64/R/library/desc/tests/testthat/test-read.R
/usr/lib64/R/library/desc/tests/testthat/test-remotes.R
/usr/lib64/R/library/desc/tests/testthat/test-repair.R
/usr/lib64/R/library/desc/tests/testthat/test-str.R
/usr/lib64/R/library/desc/tests/testthat/test-to_latex.R
/usr/lib64/R/library/desc/tests/testthat/test-trailing-ws.R
/usr/lib64/R/library/desc/tests/testthat/test-urls.R
/usr/lib64/R/library/desc/tests/testthat/test-utils.R
/usr/lib64/R/library/desc/tests/testthat/test-validation.R
/usr/lib64/R/library/desc/tests/testthat/test-versions.R
/usr/lib64/R/library/desc/tests/testthat/test-write.R
